### ISSUE TITLE
Can't "Open" this lab

### ISSUE THREAD

**Issue by Rollo510** [learn-co-curriculum/prototypal-oo-js-object-oriented-constructor-functions-lab#4]
I've tried signing out, refreshing the page, going in through GitHub; I'm unable to get this lesson to recognize that I've "opened" the lab, even though I completed it and submitted it via VSC already.  Basically, the lesson isn't showing as completed.

**Comment by graciemcguire** [comment]
Thanks for raising this issue. Based on your description, it sounds like the issue may be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
